import React, { useContext, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { ConnectNostr } from "./wallet/connect-nostr";
import { NostrClientContext } from "@/context/nostr-client";
import { Client } from "@rust-nostr/nostr-sdk";
import { relayUrl } from "@/lib/relay";

type LayoutProps = {
  children: React.ReactNode;
  title?: string;
  description?: string;
};

const Layout: React.FC<LayoutProps> = ({
  children,
  title = "CKB Next APP",
  description = "Generated by create next app",
}) => {
  const { nostrReadClient, setNostrReadClient } =
    useContext(NostrClientContext);

  // init nostr read client if not ready
  useEffect(() => {
    if (!nostrReadClient) {
      let client = new Client();
      client.addRelay(relayUrl).then(() => {
        client.connect();
      });
      setNostrReadClient(client);
    }
  }, [nostrReadClient]);

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
      </Head>
      <div className="max-w-screen-md mx-auto mt-10">
        <div className="flex justify-between">
          <Link
            href={"/"}
            className="no-underline text-3xl font-bold cursor-pointer"
          >
            NosBook
          </Link>
          <ConnectNostr />
        </div>

        <main>{children}</main>
        <div className="my-12 text-gray-500 italic">
          <hr className="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700" />
          This template is created by{" "}
          <a
            href="https://github.com/RetricSu/offckb"
            target="_blank"
            rel="noopener noreferrer"
          >
            offckb
          </a>
        </div>
      </div>
    </div>
  );
};

export default Layout;
