import "../styles/globals.css";

import type { AppProps } from "next/app";
import offckb from "@/offckb.config";
import { Client, loadWasmSync, NostrSigner } from "@rust-nostr/nostr-sdk";
import { useState } from "react";
import { CKBSigner, SingerContext } from "../context/signer";
import { NostrClientContext } from "../context/nostr-client";
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

offckb.initializeLumosConfig();

// init wasm nostr sdk
loadWasmSync();

export default function MyApp({ Component, pageProps }: AppProps) {
  const [nostrSigner, setNostrSigner] = useState<
    NostrSigner | null | undefined
  >(null);
  const [ckbSigner, setCKBSigner] = useState<CKBSigner | null | undefined>(
    null,
  );
  const signerValue = { nostrSigner, setNostrSigner, ckbSigner, setCKBSigner };

  const [nostrReadClient, setNostrReadClient] = useState<
    Client | null | undefined
  >(null);
  const [nostrWriteClient, setNostrWriteClient] = useState<
    Client | null | undefined
  >(null);
  const nostrClientValue = {
    nostrReadClient,
    setNostrReadClient,
    nostrWriteClient,
    setNostrWriteClient,
  };

  return (
    <SingerContext.Provider value={signerValue}>
      <NostrClientContext.Provider value={nostrClientValue}>
        <Head>
          <title>CKB Next APP</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className={inter.className}>
          <Component {...pageProps} />
        </div>
      </NostrClientContext.Provider>
    </SingerContext.Provider>
  );
}
